manifest:
  remotes:
    - name: origin
      url-base: https://github.com/boardmacro
  projects:
    - name: zmk-config-van75
      path: zmk-config-van75
      revision: master
      remote: origin
